function Enable-DecomLitigationHold {
    param([pscustomobject]$Context,[System.Management.Automation.PSCmdlet]$Cmdlet)
    if($Context.WhatIf){return New-DecomSkippedBecauseWhatIf -ActionName 'Enable Litigation Hold' -Phase 'Compliance' -TargetUPN $Context.TargetUPN -RecommendedNext 'Evaluate license removal readiness'}
    try{$before=Get-EXOMailbox -Identity $Context.TargetUPN -ErrorAction Stop|Select-Object LitigationHoldEnabled,LitigationHoldDuration,ArchiveStatus; if($before.LitigationHoldEnabled -ne $true -and $Cmdlet.ShouldProcess($Context.TargetUPN,'Enable Litigation Hold')){Set-Mailbox -Identity $Context.TargetUPN -LitigationHoldEnabled $true}; $after=Get-EXOMailbox -Identity $Context.TargetUPN -ErrorAction Stop|Select-Object LitigationHoldEnabled,LitigationHoldDuration,ArchiveStatus; $r=New-DecomActionResult -ActionName 'Enable Litigation Hold' -Phase 'Compliance' -Status 'Success' -IsCritical $true -TargetUPN $Context.TargetUPN -Message 'Litigation Hold enabled or already present.' -BeforeState $before -AfterState $after -Evidence @{LitigationHoldEnabled=$after.LitigationHoldEnabled} -ControlObjective 'Preserve regulated mailbox evidence' -RiskMitigated 'Data loss before retention requirements are satisfied'; Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $true -Message $r.Message -BeforeState $before -AfterState $after -Evidence $r.Evidence|Out-Null; $r}
    catch{$r=New-DecomActionResult -ActionName 'Enable Litigation Hold' -Phase 'Compliance' -Status 'Failed' -IsCritical $true -TargetUPN $Context.TargetUPN -Message $_.Exception.Message -BlockerMessages @('Failed to enable Litigation Hold.'); Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $true -Message $r.Message -ErrorRecord $_|Out-Null; $r}
}
function Get-DecomComplianceState {
    param([pscustomobject]$Context)
    try{$mbx=Get-EXOMailbox -Identity $Context.TargetUPN -ErrorAction Stop|Select-Object LitigationHoldEnabled,InPlaceHolds,RetentionHoldEnabled,ArchiveStatus,RecipientTypeDetails,ComplianceTagHoldApplied; $ev=@{LitigationHoldEnabled=$mbx.LitigationHoldEnabled; InPlaceHoldCount=@($mbx.InPlaceHolds).Count; RetentionHoldEnabled=$mbx.RetentionHoldEnabled; ArchiveStatus=$mbx.ArchiveStatus; ComplianceTagHoldApplied=$mbx.ComplianceTagHoldApplied; RecipientTypeDetails=$mbx.RecipientTypeDetails}; $warnings=@(); if($mbx.ArchiveStatus -and $mbx.ArchiveStatus -ne 'None'){$warnings+='Archive mailbox exists; license removal requires tenant-specific validation.'}; if(@($mbx.InPlaceHolds).Count -gt 0){$warnings+='In-place or Purview-originated hold indicators detected.'}; $status=if($warnings.Count -gt 0){'Warning'}else{'Success'}; $r=New-DecomActionResult -ActionName 'Evaluate Compliance State' -Phase 'Compliance' -Status $status -IsCritical $false -TargetUPN $Context.TargetUPN -Message 'Compliance state evaluated.' -Evidence $ev -WarningMessages $warnings -ControlObjective 'Identify compliance blockers before license mutation' -RiskMitigated 'Premature license removal under retention or hold conditions'; Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $false -Message $r.Message -Evidence $ev|Out-Null; $r}
    catch{$r=New-DecomActionResult -ActionName 'Evaluate Compliance State' -Phase 'Compliance' -Status 'Warning' -IsCritical $false -TargetUPN $Context.TargetUPN -Message $_.Exception.Message -WarningMessages @('Unable to fully evaluate compliance state.'); Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $false -Message $r.Message -ErrorRecord $_|Out-Null; $r}
}
Export-ModuleMember -Function Enable-DecomLitigationHold,Get-DecomComplianceState
