function Convert-DecomMailboxToShared {
    param([pscustomobject]$Context,[System.Management.Automation.PSCmdlet]$Cmdlet)
    if($Context.WhatIf){return New-DecomSkippedBecauseWhatIf -ActionName 'Convert Mailbox To Shared' -Phase 'Mailbox' -TargetUPN $Context.TargetUPN -RecommendedNext 'Set auto reply'}
    try{$before=Get-EXOMailbox -Identity $Context.TargetUPN -ErrorAction Stop|Select-Object Identity,RecipientTypeDetails,ArchiveStatus,LitigationHoldEnabled; if($before.RecipientTypeDetails -eq 'SharedMailbox'){$status='Success';$msg='Mailbox is already shared.'} elseif($Cmdlet.ShouldProcess($Context.TargetUPN,'Convert mailbox to shared')){Set-Mailbox -Identity $Context.TargetUPN -Type Shared; $status='Success';$msg='Mailbox converted to shared.'}; $after=Get-EXOMailbox -Identity $Context.TargetUPN -ErrorAction Stop|Select-Object Identity,RecipientTypeDetails,ArchiveStatus,LitigationHoldEnabled; $r=New-DecomActionResult -ActionName 'Convert Mailbox To Shared' -Phase 'Mailbox' -Status $status -IsCritical $true -TargetUPN $Context.TargetUPN -Message $msg -BeforeState $before -AfterState $after -Evidence @{ConvertedOrAlreadyShared=($after.RecipientTypeDetails -eq 'SharedMailbox')} -ControlObjective 'Preserve mailbox continuity before license mutation' -RiskMitigated 'Mailbox loss or access disruption'; Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $true -Message $r.Message -BeforeState $before -AfterState $after -Evidence $r.Evidence|Out-Null; $r}
    catch{$r=New-DecomActionResult -ActionName 'Convert Mailbox To Shared' -Phase 'Mailbox' -Status 'Failed' -IsCritical $true -TargetUPN $Context.TargetUPN -Message $_.Exception.Message -BlockerMessages @('Mailbox conversion failed.'); Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $true -Message $r.Message -ErrorRecord $_|Out-Null; $r}
}
function Set-DecomAutoReply {
    param([pscustomobject]$Context,[string]$Message,[System.Management.Automation.PSCmdlet]$Cmdlet)
    if([string]::IsNullOrWhiteSpace($Message)){return New-DecomActionResult -ActionName 'Set Out-of-Office' -Phase 'Mailbox' -Status 'Skipped' -IsCritical $false -TargetUPN $Context.TargetUPN -Message 'No out-of-office message provided.' -RecommendedNext 'Continue compliance evaluation'}
    if($Context.WhatIf){return New-DecomSkippedBecauseWhatIf -ActionName 'Set Out-of-Office' -Phase 'Mailbox' -TargetUPN $Context.TargetUPN -RecommendedNext 'Continue compliance evaluation'}
    try{if($Cmdlet.ShouldProcess($Context.TargetUPN,'Set mailbox auto-reply')){Set-MailboxAutoReplyConfiguration -Identity $Context.TargetUPN -AutoReplyState Enabled -InternalMessage $Message -ExternalMessage $Message -ExternalAudience All}; $r=New-DecomActionResult -ActionName 'Set Out-of-Office' -Phase 'Mailbox' -Status 'Success' -IsCritical $false -TargetUPN $Context.TargetUPN -Message 'Auto reply configured.' -Evidence @{AutoReplyConfigured=$true; MessageLength=$Message.Length} -ControlObjective 'Preserve business communication continuity' -RiskMitigated 'Orphaned inbound communication'; Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $false -Message $r.Message -Evidence $r.Evidence|Out-Null; $r}
    catch{$r=New-DecomActionResult -ActionName 'Set Out-of-Office' -Phase 'Mailbox' -Status 'Warning' -IsCritical $false -TargetUPN $Context.TargetUPN -Message $_.Exception.Message -WarningMessages @('Failed to configure auto reply.'); Add-DecomEvidenceEvent -Context $Context -Phase $r.Phase -ActionName $r.ActionName -Status $r.Status -IsCritical $false -Message $r.Message -ErrorRecord $_|Out-Null; $r}
}
Export-ModuleMember -Function Convert-DecomMailboxToShared,Set-DecomAutoReply
