function ConvertTo-DecomHtmlEncoded { param([object]$Value) if($null -eq $Value){return ''}; return [System.Net.WebUtility]::HtmlEncode([string]$Value) }
function Export-DecomJsonReport { param([pscustomobject]$WorkflowResult,[string]$Path) $WorkflowResult|ConvertTo-Json -Depth 30|Set-Content -Path $Path -Encoding UTF8 }
function Get-DecomStatusCounts { param([object[]]$Results) [pscustomobject]@{Success=@($Results|Where-Object Status -eq 'Success').Count; Warning=@($Results|Where-Object Status -eq 'Warning').Count; Blocked=@($Results|Where-Object Status -eq 'Blocked').Count; Failed=@($Results|Where-Object Status -eq 'Failed').Count; Skipped=@($Results|Where-Object Status -eq 'Skipped').Count} }
function Format-DecomEvidenceValue { param([object]$Value) if($null -eq $Value){return ''}; if($Value -is [string]){return $Value}; if($Value -is [System.Collections.IEnumerable] -and -not ($Value -is [string])){return (@($Value)|ForEach-Object { if($_ -is [psobject]){($_.PSObject.Properties|ForEach-Object {"$($_.Name)=$($_.Value)"}) -join '; '} else {[string]$_} }) -join ', '}; if($Value -is [psobject]){return ($Value.PSObject.Properties|ForEach-Object {"$($_.Name)=$($_.Value)"}) -join '; '}; [string]$Value }
function Get-DecomEvidenceSummary { param([hashtable]$Evidence) if(-not $Evidence -or $Evidence.Keys.Count -eq 0){return ''}; ($Evidence.Keys|ForEach-Object {"{0}: {1}" -f $_,(Format-DecomEvidenceValue -Value $Evidence[$_])}) -join ' | ' }
function Export-DecomHtmlReport {
    param([pscustomobject]$WorkflowResult,[string]$Path)
    $Counts=Get-DecomStatusCounts -Results $WorkflowResult.Results
    $rows=foreach($r in $WorkflowResult.Results){$css=switch($r.Status){'Success'{'ok'}'Warning'{'warn'}'Blocked'{'blocked'}'Failed'{'failed'}'Skipped'{'skipped'}default{'other'}}; $ev=ConvertTo-DecomHtmlEncoded (Get-DecomEvidenceSummary -Evidence $r.Evidence); "<tr class='$css'><td>$(ConvertTo-DecomHtmlEncoded $r.Phase)</td><td>$(ConvertTo-DecomHtmlEncoded $r.ActionName)</td><td>$(ConvertTo-DecomHtmlEncoded $r.Status)</td><td>$(ConvertTo-DecomHtmlEncoded $r.Message)</td><td>$ev</td><td>$(ConvertTo-DecomHtmlEncoded $r.ControlObjective)</td></tr>"}
$html=@"
<html><head><title>Entra Identity Decommissioning Evidence Report</title><style>body{font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#172033}table{border-collapse:collapse;width:100%;margin-top:16px}th,td{border:1px solid #d6dbe3;padding:8px;text-align:left;vertical-align:top}th{background:#eef2f7}.summary{display:grid;grid-template-columns:repeat(5,minmax(100px,1fr));gap:12px;margin:16px 0}.card{border:1px solid #d6dbe3;border-radius:8px;padding:12px;background:#f8fafc}tr.ok td{background:#eef9f0}tr.warn td{background:#fff8e5}tr.blocked td,tr.failed td{background:#fff0f0}tr.skipped td{background:#f3f3f3}.small{color:#555;font-size:12px}</style></head><body><h1>Entra Identity Decommissioning Evidence Report</h1><p><strong>Target:</strong> $(ConvertTo-DecomHtmlEncoded $WorkflowResult.Context.TargetUPN)</p><p><strong>Run ID:</strong> $(ConvertTo-DecomHtmlEncoded $WorkflowResult.State.RunId)</p><p><strong>Version:</strong> v1.0</p><div class='summary'><div class='card'><strong>Success</strong><br>$($Counts.Success)</div><div class='card'><strong>Warning</strong><br>$($Counts.Warning)</div><div class='card'><strong>Blocked</strong><br>$($Counts.Blocked)</div><div class='card'><strong>Failed</strong><br>$($Counts.Failed)</div><div class='card'><strong>Skipped</strong><br>$($Counts.Skipped)</div></div><table><thead><tr><th>Phase</th><th>Action</th><th>Status</th><th>Message</th><th>Evidence</th><th>Control Objective</th></tr></thead><tbody>$(($rows -join "`n"))</tbody></table><p class='small'>© 2026 Albert Jee. All rights reserved.</p></body></html>
"@
    Set-Content -Path $Path -Value $html -Encoding UTF8
}
Export-ModuleMember -Function Export-DecomJsonReport,Get-DecomStatusCounts,Format-DecomEvidenceValue,Get-DecomEvidenceSummary,Export-DecomHtmlReport,ConvertTo-DecomHtmlEncoded
