# BatchApproval.psm1 — Pre-flight approval gate
# Premium v2.1 — Feature 3
#
# Functions:
#   Invoke-DecomBatchApproval  — halts batch and requires explicit operator ACK
#   New-DecomApprovalRecord    — creates a signed approval record for audit trail
#   Get-DecomApprovalStatus    — reads the approval record from disk
#
# Design:
#   Before Invoke-DecomBatch runs destructive phases, callers can invoke
#   Invoke-DecomBatchApproval to enforce a gate. The gate:
#     1. Displays a pre-flight summary (UPN count, risk flags, ticket)
#     2. In interactive mode: prompts operator for explicit 'YES' confirmation
#     3. In NonInteractive mode: requires a pre-signed approval file
#        (generated by New-DecomApprovalRecord and passed via -ApprovalPath)
#     4. Writes an approval record to <BatchDir>\batch-approval.json
#     5. Returns $true (approved) or throws (not approved)
#
#   The approval record is included in the batch evidence manifest (Phase 2)
#   for full non-repudiation chain.
#
# PS7 compatible (v2.1 baseline)

#Requires -Version 7.0

Set-StrictMode -Version Latest

# ── Public API ─────────────────────────────────────────────────────────────────

function Invoke-DecomBatchApproval {
    <#
    .SYNOPSIS
        Enforces a pre-flight approval gate before destructive batch execution.

    .DESCRIPTION
        Interactive mode:
          Displays batch summary and prompts the operator to type 'YES' to
          proceed. Any other input aborts the batch.

        NonInteractive mode (-NonInteractive):
          Requires a pre-signed approval file passed via -ApprovalPath.
          The file must have been created by New-DecomApprovalRecord and must
          match the BatchId of the current batch. Throws if missing or mismatched.

        In both modes, a batch-approval.json is written to the batch directory
        for the audit trail.

    .PARAMETER Batch
        The batch envelope.

    .PARAMETER NonInteractive
        Switch to require a pre-signed approval file instead of interactive prompt.

    .PARAMETER ApprovalPath
        Path to a pre-signed approval JSON file (required when -NonInteractive).

    .PARAMETER ApproverUPN
        Approver identity for the approval record. Defaults to Batch.OperatorUPN.

    .OUTPUTS
        [bool] — $true if approved. Throws if not approved.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][pscustomobject]$Batch,
        [switch]$NonInteractive,
        [string]$ApprovalPath,
        [string]$ApproverUPN
    )

    $batchDir    = Join-Path $Batch.OutputRoot $Batch.BatchId
    $null        = New-Item -ItemType Directory -Path $batchDir -Force
    $approver    = if ($ApproverUPN) { $ApproverUPN } else { $Batch.OperatorUPN }

    if ($NonInteractive) {
        # ── Pre-signed approval path ──────────────────────────────────────────
        if (-not $ApprovalPath) {
            throw 'Invoke-DecomBatchApproval: -ApprovalPath is required in -NonInteractive mode.'
        }
        if (-not (Test-Path $ApprovalPath)) {
            throw "Invoke-DecomBatchApproval: approval file not found at '$ApprovalPath'."
        }

        $preApproval = Get-Content $ApprovalPath -Raw -Encoding UTF8 | ConvertFrom-Json

        if ($preApproval.BatchId -ne $Batch.BatchId) {
            throw ("Invoke-DecomBatchApproval: approval file BatchId '{0}' does not match current batch '{1}'." -f
                $preApproval.BatchId, $Batch.BatchId)
        }

        if ($preApproval.Approved -ne $true) {
            throw "Invoke-DecomBatchApproval: approval file does not contain Approved = true."
        }

        $approver = $preApproval.ApproverUPN

        Write-Host "[Approval] Pre-signed approval accepted from $approver" -ForegroundColor Green

    } else {
        # ── Interactive approval gate ─────────────────────────────────────────
        _WriteApprovalSummary -Batch $Batch

        Write-Host ''
        Write-Host 'Type YES to proceed with this batch, or anything else to abort:' `
            -ForegroundColor Yellow -NoNewline
        $response = Read-Host ' '

        if ($response.Trim() -ne 'YES') {
            throw "Invoke-DecomBatchApproval: batch aborted by operator. Response was: '$response'"
        }

        Write-Host '[Approval] Confirmed by operator.' -ForegroundColor Green
    }

    # ── Write approval record ─────────────────────────────────────────────────
    $record = _WriteApprovalRecord `
        -Batch     $Batch `
        -BatchDir  $batchDir `
        -Approver  $approver `
        -Method    $(if ($NonInteractive) { 'PreSigned' } else { 'Interactive' })

    return $true
}

function New-DecomApprovalRecord {
    <#
    .SYNOPSIS
        Creates a pre-signed approval JSON file for use in NonInteractive mode.

    .DESCRIPTION
        Intended for change management workflows where a manager or change board
        pre-approves a batch before the automated pipeline runs.

        The generated file contains the BatchId, approver identity, timestamp,
        and Approved = true. Pass the file path to
        Invoke-DecomBatchApproval -NonInteractive -ApprovalPath <path>.

    .PARAMETER Batch
        The batch envelope to pre-approve.

    .PARAMETER ApproverUPN
        Identity of the person signing the approval.

    .PARAMETER OutputPath
        Directory to write the approval file into.
        Defaults to <Batch.OutputRoot>\<BatchId>\.

    .OUTPUTS
        [string] — path to the written approval file.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][pscustomobject]$Batch,
        [Parameter(Mandatory)][string]$ApproverUPN,
        [string]$OutputPath
    )

    $dir = if ($OutputPath) { $OutputPath } else {
        Join-Path $Batch.OutputRoot $Batch.BatchId
    }
    $null = New-Item -ItemType Directory -Path $dir -Force

    $record = [ordered]@{
        SchemaVersion = '2.1'
        RecordType    = 'PreSignedApproval'
        BatchId       = $Batch.BatchId
        TicketId      = $Batch.TicketId
        ApproverUPN   = $ApproverUPN
        Approved      = $true
        ApprovedUtc   = (Get-Date).ToUniversalTime().ToString('o')
        UPNCount      = $Batch.Entries.Count
        Note          = 'Pre-signed approval for NonInteractive batch execution.'
    }

    $path = Join-Path $dir 'batch-approval-presigned.json'
    $record | ConvertTo-Json -Depth 5 | Set-Content -Path $path -Encoding UTF8
    return $path
}

function Get-DecomApprovalStatus {
    <#
    .SYNOPSIS
        Reads and returns the approval record for a batch from disk.
        Returns $null if no approval record exists yet.

    .PARAMETER Batch
        The batch envelope.

    .OUTPUTS
        [pscustomobject] approval record, or $null.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][pscustomobject]$Batch
    )

    $path = Join-Path (Join-Path $Batch.OutputRoot $Batch.BatchId) 'batch-approval.json'
    if (-not (Test-Path $path)) { return $null }

    return Get-Content $path -Raw -Encoding UTF8 | ConvertFrom-Json
}

# ── Private helpers ────────────────────────────────────────────────────────────

function _WriteApprovalSummary {
    param([pscustomobject]$Batch)

    Write-Host ''
    Write-Host '── Batch Pre-flight Summary ─────────────────────────────' -ForegroundColor Cyan
    Write-Host ("  Batch ID  : {0}" -f $Batch.BatchId)      -ForegroundColor White
    Write-Host ("  Ticket    : {0}" -f $(if ($Batch.TicketId) { $Batch.TicketId } else { 'none' })) -ForegroundColor White
    Write-Host ("  Operator  : {0}" -f $Batch.OperatorUPN)  -ForegroundColor White
    Write-Host ("  UPNs      : {0}" -f $Batch.Entries.Count) -ForegroundColor White
    Write-Host ("  Evidence  : {0}" -f $Batch.EvidenceLevel) -ForegroundColor White
    Write-Host ("  Mode      : {0}" -f $(if ($Batch.WhatIf) { 'WhatIf (no mutations)' } else { 'LIVE — mutations will occur' })) `
        -ForegroundColor $(if ($Batch.WhatIf) { 'Yellow' } else { 'Red' })
    Write-Host ''
    Write-Host '  UPNs in scope:' -ForegroundColor White
    foreach ($key in $Batch.Entries.Keys) {
        Write-Host ("    · {0}" -f $Batch.Entries[$key].UPN) -ForegroundColor Gray
    }
    Write-Host '─────────────────────────────────────────────────────────' -ForegroundColor Cyan
}

function _WriteApprovalRecord {
    param([pscustomobject]$Batch, [string]$BatchDir, [string]$Approver, [string]$Method)

    $record = [ordered]@{
        SchemaVersion = '2.1'
        RecordType    = 'ApprovalRecord'
        BatchId       = $Batch.BatchId
        TicketId      = $Batch.TicketId
        ApproverUPN   = $Approver
        ApprovalMethod= $Method   # Interactive | PreSigned
        Approved      = $true
        ApprovedUtc   = (Get-Date).ToUniversalTime().ToString('o')
        UPNCount      = $Batch.Entries.Count
    }

    $path = Join-Path $BatchDir 'batch-approval.json'
    $record | ConvertTo-Json -Depth 5 | Set-Content -Path $path -Encoding UTF8
    return [pscustomobject]$record
}

Export-ModuleMember -Function `
    Invoke-DecomBatchApproval, `
    New-DecomApprovalRecord, `
    Get-DecomApprovalStatus
